import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import logout from "@/api/auth/logout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="p-2">
      <body className={inter.className}>
        <header className="mb-4">
          <form action={logout}>
            <button className="p-2 bg-neutral-200">Log out</button>
          </form>
        </header>
        {children}
      </body>
    </html>
  );
}
